version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./test.db:/app/test.db
    environment:
      - ENV=development
      - DB_TYPE=sqlite
      - DB_PATH=/app/test.db
      - PORT=8080
    restart: unless-stopped
    networks:
      - multilayer-dev-network

networks:
  multilayer-dev-network:
    driver: bridge 