version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"
    environment:
      - ENV=production
      - DB_TYPE=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=multilayer
      - PORT=8080
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - multilayer-network

  # PostgreSQL для продакшена (можно заменить на SQLite для разработки)
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=multilayer
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - multilayer-network

volumes:
  postgres_data:

networks:
  multilayer-network:
    driver: bridge 