apiVersion: v1
kind: ConfigMap
metadata:
  name: multilayer-config
  namespace: multilayer
data:
  ENV: "production"
  DB_TYPE: "postgres"
  DB_HOST: "multilayer-postgres"
  DB_PORT: "5432"
  DB_NAME: "multilayer"
  PORT: "8080" 