apiVersion: v1
kind: Service
metadata:
  name: multilayer-postgres
  namespace: multilayer
spec:
  selector:
    app: multilayer-postgres
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP 