apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: multilayer-postgres-pvc
  namespace: multilayer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
#  storageClassName: csi-cinder-sc-delete 